Repository rohtable/movieFeed, pull requests merged in 2024-06, with the labels that each got.

#10 gitignore update & Board entity create
  .gitignore
  gradlew
  src/main/java/com/sparta/moviefeed/entity/Board.java
Labels: documentation

#12 feat : 게시글 등록 기능 구현
  src/main/java/com/sparta/moviefeed/controller/BoardController.java
  src/main/java/com/sparta/moviefeed/dto/requestdto/BoardRequestDto.java
  src/main/java/com/sparta/moviefeed/dto/responsedto/BoardResponseDto.java
  src/main/java/com/sparta/moviefeed/entity/Board.java
  src/main/java/com/sparta/moviefeed/repository/BoardRepository.java
  src/main/java/com/sparta/moviefeed/service/BoardService.java
Labels: feat

#17 특정 게시글 조회 기능 구현
  src/main/java/com/sparta/moviefeed/controller/BoardController.java
  src/main/java/com/sparta/moviefeed/entity/Board.java
  src/main/java/com/sparta/moviefeed/service/BoardService.java
Labels: feat

#16 feat: 마이페이지 수정 및 비밀번호 수정 기능 구현
  src/main/java/com/sparta/moviefeed/controller/MypageController.java
  src/main/java/com/sparta/moviefeed/dto/requestdto/MypageRequestDto.java
  src/main/java/com/sparta/moviefeed/dto/requestdto/PasswordRequestDto.java
  src/main/java/com/sparta/moviefeed/dto/responsedto/CommonResponse.java
  src/main/java/com/sparta/moviefeed/entity/User.java
  src/main/java/com/sparta/moviefeed/service/MypageService.java
Labels: feat

#24 전체 게시글 조회 기능 구현
  src/main/java/com/sparta/moviefeed/MovieFeedApplication.java
  src/main/java/com/sparta/moviefeed/controller/BoardController.java
  src/main/java/com/sparta/moviefeed/dto/responsedto/BoardResponseDto.java
  src/main/java/com/sparta/moviefeed/entity/Board.java
  src/main/java/com/sparta/moviefeed/service/BoardService.java
Labels: feat

#28 feat : 게시글 삭제 기능 구현
  src/main/java/com/sparta/moviefeed/controller/BoardController.java
  src/main/java/com/sparta/moviefeed/dto/responsedto/BoardResponseDto.java
  src/main/java/com/sparta/moviefeed/entity/Board.java
  src/main/java/com/sparta/moviefeed/service/BoardService.java
Labels: feat

#29 feat: 이메일 가입 및 인증 구현
  build.gradle
  src/main/java/com/sparta/moviefeed/config/EmailConfig.java
  src/main/java/com/sparta/moviefeed/controller/EmailController.java
  src/main/java/com/sparta/moviefeed/dto/requestdto/EmailCheckRequestDto.java
  src/main/java/com/sparta/moviefeed/dto/requestdto/EmailRequestDto.java
  src/main/java/com/sparta/moviefeed/service/EmailService.java
  src/main/java/com/sparta/moviefeed/service/RedisUtil.java
  src/main/resources/application.properties
Labels: feat

#37 feat : 좋아요 추가 기능 구현
  src/main/java/com/sparta/moviefeed/controller/BoardController.java
  src/main/java/com/sparta/moviefeed/entity/Board.java
  src/main/java/com/sparta/moviefeed/entity/Like.java
  src/main/java/com/sparta/moviefeed/enumeration/LikeType.java
  src/main/java/com/sparta/moviefeed/exception/GlobalExceptionHandler.java
  src/main/java/com/sparta/moviefeed/exception/ViolatedLikeException.java
  src/main/java/com/sparta/moviefeed/repository/LikeRepository.java
  src/main/java/com/sparta/moviefeed/service/BoardService.java
Labels: feat

#58 update: 이메일 인증/인가 추가 및 회원코드 변경
  src/main/java/com/sparta/moviefeed/controller/EmailController.java
  src/main/java/com/sparta/moviefeed/dto/requestdto/EmailRequestDto.java
  src/main/java/com/sparta/moviefeed/enumeration/UserStatus.java
  src/main/java/com/sparta/moviefeed/service/EmailService.java
  src/main/java/com/sparta/moviefeed/service/RedisUtil.java
Labels: update

#60 docs : README 작성
  README.md
Labels: documentation

#62 docs : 프로젝트 후기
  README.md
Labels: documentation
